export default [
    {id: '1', imageName: 'foto1.jpg', tag: 'instalação'},
    {id: '2', imageName: 'foto2.jpg', tag: 'instalação'},
    {id: '3', imageName: 'foto3.jpg', tag: 'instalação'},
    {id: '4', imageName: 'foto4.jpg', tag: 'canário'},
    {id: '5', imageName: 'foto5.jpg', tag: 'canário'},
    {id: '6', imageName: 'foto6.jpg', tag: 'canário'},
    {id: '7', imageName: 'foto7.jpg', tag: 'canário'},
    {id: '8', imageName: 'foto8.jpg', tag: 'canário'},
    {id: '9', imageName: 'foto9.jpg', tag: 'canário'},
    {id: '10', imageName: 'foto10.jpg', tag: 'ração'},
    {id: '11', imageName: 'foto11.jpg', tag: 'ração'},
    {id: '12', imageName: 'foto12.jpg', tag: 'ração'},
    {id: '13', imageName: 'foto13.jpg', tag: 'ração'},
];